heat_template_version: 2015-10-15

description: Basic Heat template for Chameleon

parameters:
  image_id:
    type: string
    description: Name or ID of the image to launch
    default: CC-Ubuntu14.04
    constraints:
    - custom_constraint: glance.image
  instance_type:
    type: string
    description: Instance type to launch
    default: baremetal
    constraints:
    - custom_constraint: nova.flavor
  key_name:
    type: string
    description: Name of a KeyPair to enable SSH access to the instance
    default: azhar2-key
  network_id:
    type: string
    description: ID of the network to use
    default: 915853fe-10c5-4dac-a402-ef1ebc53e427

  reservation_id:
    type: string
    description: ID of the Blazar reservation to use for launching instances.
    default: 359852fb-e5ff-47eb-8f9b-989ed611c025 

resources:
  control_node:
    type: OS::Nova::Server2
    properties:
      instance_type: { get_param: instance_type }
      image_id: { get_param: image_id }
      key_name: { get_param: key_name }
      network_id: { get_param: network_id }
      reservation_id: { get_param: reservation_id }

  compute_node:
    type: OS::Nova::Server3
    properties:
      instance_type: { get_param: instance_type }
      image_id: { get_param: image_id }
      key_name: { get_param: key_name }
      network_id: { get_param: network_id }
      reservation_id: { get_param: reservation_id }
      master:
        get_attr:
          - control_node
          - instance1_ip
